version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  rust: circleci/rust@1.5.0
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  production:
    # Run the welcome/run job in its own container
    jobs:
      - rust/lint-test-build:
          release: true
